name = "2bim-avalia1-cleinaldo-bretas"
compatibility_date = "2026-10-07"

[assets]
directory = "./"
not_found_handling = "single-pages-application"

[var]
GOOGLE_CLIENT_ID = "626344497877-vrokq3fhbn9cmipktbmhppvt8fjk7gon.apps.googleusercontent.com"
